# 网站标题
title: 工具

# 网站的描述
description: Tools

# 网站的基本 URL
url: https://tools.hainansec.com

# 网站的根目录
baseurl: ""

# 使用的 Jekyll 主题
theme: jekyll-theme-shell

# 用于设置访问网站时使用的语言
lang: en-US

# 用于配置插件
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

# 用于指定需要拷贝的文件
include_files:
  - _assets/css/*
  - _assets/js/*
  - _assets/img/*

# Markdown 配置
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: highlight

# Github Pages 配置
github:
  is_project_page: false

# Google Analytics 配置
# analytics_tracking_id: UA-123456789-0
